var apifan = 'ecb3947c7bf1bc176d52128a82376f85' // FanArt.tv API KEY
var apiv = '' // Radarr API KEY
var apis = '' // Sonarr API KEY
var tmdbapi = '01e113a071c57ddf8fa6b5a06c0a9fdc' // TheMovieDb API KEY
var tvdbapikey = '' // TheTVDB API KEY
var tvdbuserkey = '' // TheTVDB Account Identifier
var tvdbusername = '' // Your TheTVDB username 
var radarrurl = '../demodata/movies.json' // Your Radarr URL
var sonarrurl = '../demodata/series.json' // Your Sonarr URL
var statusurl = '../demodata/status.json' // Your Radarr URL with /api/system/status
